name: Linux_x86_64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install GNU 13 compiler suite
      run: |
        sudo apt update
        sudo apt install -y gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 110 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        uname -a
        g++ --version | grep g++

    - name: Run CMake
      run: |
        cd build && ./cmLinux.sh && cd ..

    - name: Run GNU Make with GNU compiler
      run: |
        cd build/LinuxRelease && make && cd ../..

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts_Linux_x86_64
        path: build/LinuxRelease/ubuntu_fetcher
