# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name:  wxMSW_x86_64_MSBuild

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

env:
  BUILD_CONFIGURATION: Debug
  BUILD_TYPE: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Execute CMake
      run: cd build && cm64.bat && cd ..

    - name: Run MSBuild
      run: |
        cd build\Win && msbuild ubuntu_fetcher.sln && cd ..\..

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts_wxMSW_x86_64_MSBuild
        path: build/bin/Debug/
