name: wxOSX_arm64

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    branches: '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run CMake
      run: |
        cd build
        chmod +x ./cmAppleMac.sh
        ./cmAppleMac.sh
        cd ..

    - name: Run GNU Make with GNU compiler
      run: |
        cd build
        mkdir -p bin
        mkdir -p bin/Debug
        cd Mac
        make VERBOSE=1 -j$(getconf _NPROCESSORS_ONLN)

    - name: Test the program and collect output
      run: |
        cd build/bin/ubuntu_fetcher.app/Contents && ./ubuntu_fetcher --list-releases > sample_output.txt && cd ../../..

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts_wxOSX_arm64
        path: build/bin/ubuntu_fetcher.app/Contents
